<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="3" total="10" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="3494" started-at="2020-04-17T13:14:33 IST" finished-at="2020-04-17T13:14:36 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="3494" started-at="2020-04-17T13:14:33 IST" finished-at="2020-04-17T13:14:36 IST">
      <class name="com.employeecheck.testcases.TC003_PostEmployeeRecord">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.employeecheck.testcases.TC003_PostEmployeeRecord@7d0587f1]" name="setup" is-config="true" duration-ms="1" started-at="2020-04-17T13:14:34 IST" finished-at="2020-04-17T13:14:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getAllEmployees()[pri:0, instance:com.employeecheck.testcases.TC003_PostEmployeeRecord@7d0587f1]" name="getAllEmployees" is-config="true" duration-ms="848" started-at="2020-04-17T13:14:34 IST" finished-at="2020-04-17T13:14:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployees -->
        <test-method status="PASS" signature="checkResponseBody()[pri:0, instance:com.employeecheck.testcases.TC003_PostEmployeeRecord@7d0587f1]" name="checkResponseBody" duration-ms="304" started-at="2020-04-17T13:14:35 IST" finished-at="2020-04-17T13:14:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method status="PASS" signature="checkStatusCode()[pri:0, instance:com.employeecheck.testcases.TC003_PostEmployeeRecord@7d0587f1]" name="checkStatusCode" duration-ms="2" started-at="2020-04-17T13:14:35 IST" finished-at="2020-04-17T13:14:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusCode -->
        <test-method status="PASS" signature="getAllEmployeesClosure()[pri:0, instance:com.employeecheck.testcases.TC003_PostEmployeeRecord@7d0587f1]" name="getAllEmployeesClosure" is-config="true" duration-ms="0" started-at="2020-04-17T13:14:35 IST" finished-at="2020-04-17T13:14:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployeesClosure -->
      </class> <!-- com.employeecheck.testcases.TC003_PostEmployeeRecord -->
      <class name="com.employeecheck.testcases.TC004_DeleteEmployeeRecord">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.employeecheck.testcases.TC004_DeleteEmployeeRecord@5d76b067]" name="setup" is-config="true" duration-ms="1" started-at="2020-04-17T13:14:35 IST" finished-at="2020-04-17T13:14:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getAllEmployees()[pri:0, instance:com.employeecheck.testcases.TC004_DeleteEmployeeRecord@5d76b067]" name="getAllEmployees" is-config="true" duration-ms="872" started-at="2020-04-17T13:14:35 IST" finished-at="2020-04-17T13:14:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployees -->
        <test-method status="SKIP" signature="checkDeleteReponse()[pri:0, instance:com.employeecheck.testcases.TC004_DeleteEmployeeRecord@5d76b067]" name="checkDeleteReponse" duration-ms="3" retried="true" started-at="2020-04-17T13:14:36 IST" finished-at="2020-04-17T13:14:36 IST">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at com.employeecheck.testcases.TC004_DeleteEmployeeRecord.checkDeleteReponse(TC004_DeleteEmployeeRecord.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDeleteReponse -->
        <test-method status="SKIP" signature="checkDeleteReponse()[pri:0, instance:com.employeecheck.testcases.TC004_DeleteEmployeeRecord@5d76b067]" name="checkDeleteReponse" duration-ms="1" retried="true" started-at="2020-04-17T13:14:36 IST" finished-at="2020-04-17T13:14:36 IST">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at com.employeecheck.testcases.TC004_DeleteEmployeeRecord.checkDeleteReponse(TC004_DeleteEmployeeRecord.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDeleteReponse -->
        <test-method status="SKIP" signature="checkDeleteReponse()[pri:0, instance:com.employeecheck.testcases.TC004_DeleteEmployeeRecord@5d76b067]" name="checkDeleteReponse" duration-ms="2" retried="true" started-at="2020-04-17T13:14:36 IST" finished-at="2020-04-17T13:14:36 IST">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at com.employeecheck.testcases.TC004_DeleteEmployeeRecord.checkDeleteReponse(TC004_DeleteEmployeeRecord.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDeleteReponse -->
        <test-method status="FAIL" signature="checkDeleteReponse()[pri:0, instance:com.employeecheck.testcases.TC004_DeleteEmployeeRecord@5d76b067]" name="checkDeleteReponse" duration-ms="1" started-at="2020-04-17T13:14:36 IST" finished-at="2020-04-17T13:14:36 IST">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at com.employeecheck.testcases.TC004_DeleteEmployeeRecord.checkDeleteReponse(TC004_DeleteEmployeeRecord.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkDeleteReponse -->
        <test-method status="PASS" signature="getAllEmployeesClosure()[pri:0, instance:com.employeecheck.testcases.TC004_DeleteEmployeeRecord@5d76b067]" name="getAllEmployeesClosure" is-config="true" duration-ms="1" started-at="2020-04-17T13:14:36 IST" finished-at="2020-04-17T13:14:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployeesClosure -->
      </class> <!-- com.employeecheck.testcases.TC004_DeleteEmployeeRecord -->
      <class name="com.employeecheck.testcases.TC001_GetAllEmployees">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.employeecheck.testcases.TC001_GetAllEmployees@67205a84]" name="setup" is-config="true" duration-ms="35" started-at="2020-04-17T13:14:33 IST" finished-at="2020-04-17T13:14:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getAllEmployees()[pri:0, instance:com.employeecheck.testcases.TC001_GetAllEmployees@67205a84]" name="getAllEmployees" is-config="true" duration-ms="1235" started-at="2020-04-17T13:14:33 IST" finished-at="2020-04-17T13:14:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployees -->
        <test-method status="PASS" signature="checkResponseBody()[pri:0, instance:com.employeecheck.testcases.TC001_GetAllEmployees@67205a84]" name="checkResponseBody" duration-ms="26" started-at="2020-04-17T13:14:34 IST" finished-at="2020-04-17T13:14:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method status="PASS" signature="checkResponseTime()[pri:0, instance:com.employeecheck.testcases.TC001_GetAllEmployees@67205a84]" name="checkResponseTime" duration-ms="1" started-at="2020-04-17T13:14:34 IST" finished-at="2020-04-17T13:14:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method status="PASS" signature="checkServerType()[pri:0, instance:com.employeecheck.testcases.TC001_GetAllEmployees@67205a84]" name="checkServerType" duration-ms="1" started-at="2020-04-17T13:14:34 IST" finished-at="2020-04-17T13:14:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkServerType -->
        <test-method status="PASS" signature="checkStatusCode()[pri:0, instance:com.employeecheck.testcases.TC001_GetAllEmployees@67205a84]" name="checkStatusCode" duration-ms="1" started-at="2020-04-17T13:14:34 IST" finished-at="2020-04-17T13:14:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkStatusCode -->
        <test-method status="PASS" signature="getAllEmployeesClosure()[pri:0, instance:com.employeecheck.testcases.TC001_GetAllEmployees@67205a84]" name="getAllEmployeesClosure" is-config="true" duration-ms="1" started-at="2020-04-17T13:14:34 IST" finished-at="2020-04-17T13:14:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllEmployeesClosure -->
      </class> <!-- com.employeecheck.testcases.TC001_GetAllEmployees -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
